name = "foo"
version = "1.0.0"
type="site"
output="html"

[deployment]
permission = "private"
nodes = 4

[build]
dir = "build"
entry = "foo_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "foo.wasm"
command = "npm run build:release"
